//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoSharingDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagInformation
    {
        public int TagInformationID { get; set; }
        public string UserUserID { get; set; }
        public int PhotoId { get; set; }
    }
}
